### ISSUE TITLE
Use a custom "Shelterly Starting" or "Loading" Page instead of "Page Not Found" when instance is warming up.

### ISSUE THREAD

**Issue by trevorskaggs** [trevorskaggs/shelterly#261] opened 2021-03-17 16:40 UTC
Currently, we get the following when Lambda/RDS is not quite warmed up yet:

![image](https://user-images.githubusercontent.com/1276123/111504062-896a5c00-8704-11eb-90cb-64b204c3c92c.png)
 

Would be nice to have a Sheltelry Loading/Starting page with a Spinner until we are ready to rock

**Comment by AlexMountain** [comment] 2021-03-17 17:16
Is this a dupe of https://github.com/trevorskaggs/shelterly/issues/258 but with a picture?

**Comment by AlexMountain** [comment] 2021-03-17 17:24
Do you envision two separate solutions to these issues?  Is there a way to start up the Aurora DB at the same time our instance is warming up?

**Comment by trevorskaggs** [comment] 2021-03-17 17:25
The solution for this one very well may resolve #258.  And just adding a "warmup" to the lambda job might actually resolve this problem, but just wanted to get it out there as I have run into it a few times during demos that I end up with a "page not found" and have to refresh a couple times!

**Comment by AlexMountain** [comment] 2021-03-17 17:58
Thanks for elaborating.  I thought about this some more because it seemed weird to me that it looks like it's able to serve our PageNotFound page but not our Login page.  Then I realized our Home page is technically one of our private routes, so that would explain PageNotFound when trying to hit the homepage while logged out.  If this issue is what I'm thinking, then maybe we can just solve with a proper redirect in the list of public routes: `'/': () => <Redirect to={'/login'} />,`

**Comment by AlexMountain** [comment] 2021-03-17 18:25
Tested it locally and no go.  Our auth checking logic is happening before we hit the router fork, so the delay is the same as Robbies ticket - the DB spinning up - because you likely have a stale token it's trying to validate with the DB before deciding what to do next.

I wonder if the solution here is to just make our homepage have the login form and fork the display on the homepage depending on whether or not the user is logged in to either show the login form vs whatever other information we finally splat there.

**Comment by AlexMountain** [comment] 2021-03-17 18:53
@trevorskaggs Please give https://github.com/trevorskaggs/shelterly/pull/262 a shot when you have a chance and let me know what you think and if it's working as expected.

**Closed** 2021-03-22 02:04 UTC
